#!/usr/bin/env python3
"""
Upload data to Zoho Creator via REST API v2.1.

Reads CSV files and pushes records to Zoho Creator forms. Runs in mock
mode by default (validates everything, logs what would be sent, no API
calls). Use --live to actually push records.

Platform: Cross-platform (stdlib only -- uses urllib.request, not requests)

Usage:
    python tools/upload_to_creator.py --config config/zoho-api.yaml --csv-dir exports/csv/
    python tools/upload_to_creator.py --config config/zoho-api.yaml --csv-dir exports/csv/ --live
    python tools/upload_to_creator.py --config config/zoho-api.yaml --json-dir config/seed-data/
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path


# ============================================================
# Constants
# ============================================================

MAX_BATCH_SIZE = 200  # Zoho API limit per request
MAX_RETRIES = 4
BACKOFF_BASE = 2  # seconds

# Upload order: lookup tables first, then transactions, then audit
UPLOAD_ORDER = [
    ("Departments", "departments"),
    ("Clients", "clients"),
    ("GL_Accounts", "gl_accounts"),
    ("Approval_Thresholds", "approval_thresholds"),
    ("Expense_Claims", "expense_claims"),
    ("Approval_History", "approval_history"),
]

# Fields to exclude from API payloads (auto-generated by Creator)
EXCLUDE_FIELDS = {"ID", "Added_User"}


# ============================================================
# YAML Parser (minimal, matches project convention)
# ============================================================

def parse_yaml(filepath: str) -> dict[str, str]:
    """Parse a flat key:value YAML file. No nested structures."""
    result: dict[str, str] = {}
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if ":" in line:
                key, _, value = line.partition(":")
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key and value:
                    result[key] = value
    return result


# ============================================================
# OAuth Token Management
# ============================================================

class TokenManager:
    """Manages OAuth 2.0 token refresh for Zoho API."""

    def __init__(self, config: dict[str, str]) -> None:
        self.client_id = config.get("client_id", "")
        self.client_secret = config.get("client_secret", "")
        self.refresh_token = config.get("refresh_token", "")
        self.auth_base = config.get("auth_base", "https://accounts.zoho.com")
        self.access_token: str = ""
        self.expires_at: float = 0.0

    def get_access_token(self) -> str:
        """Return a valid access token, refreshing if needed."""
        if self.access_token and time.time() < self.expires_at:
            return self.access_token

        url = f"{self.auth_base}/oauth/v2/token"
        data = (
            f"grant_type=refresh_token"
            f"&client_id={self.client_id}"
            f"&client_secret={self.client_secret}"
            f"&refresh_token={self.refresh_token}"
        ).encode("utf-8")

        req = urllib.request.Request(
            url, data=data,
            headers={"Content-Type": "application/x-www-form-urlencoded"},
        )
        try:
            with urllib.request.urlopen(req) as resp:
                body = json.loads(resp.read().decode("utf-8"))
                self.access_token = body["access_token"]
                self.expires_at = time.time() + body.get("expires_in", 3600) - 60
                return self.access_token
        except (urllib.error.URLError, KeyError) as e:
            print(f"Error refreshing token: {e}", file=sys.stderr)
            sys.exit(1)

    def validate(self) -> list[str]:
        """Validate config has required fields. Returns list of errors."""
        errors: list[str] = []
        for field in ("client_id", "client_secret", "refresh_token"):
            val = getattr(self, field, "")
            if not val:
                errors.append(f"Missing required config: {field}")
        return errors


# ============================================================
# API Client
# ============================================================

class CreatorAPI:
    """Zoho Creator REST API v2.1 client."""

    def __init__(self, config: dict[str, str], token_mgr: TokenManager, live: bool = False) -> None:
        self.owner = config.get("owner", "")
        self.app = config.get("app", "")
        self.api_base = config.get("api_base", "https://creator.zoho.com/api/v2.1")
        self.token_mgr = token_mgr
        self.live = live

    def add_records(self, form_name: str, records: list[dict]) -> dict:
        """Add records to a form. Returns API response or mock response."""
        url = f"{self.api_base}/{self.owner}/{self.app}/form/{form_name}/record"

        if len(records) == 1:
            payload = {"data": records[0]}
        else:
            payload = {"data": records}

        body = json.dumps(payload).encode("utf-8")

        if not self.live:
            return {
                "mock": True,
                "url": url,
                "records": len(records),
                "code": 3000,
            }

        token = self.token_mgr.get_access_token()
        headers = {
            "Authorization": f"Zoho-oauthtoken {token}",
            "Content-Type": "application/json",
        }

        for attempt in range(MAX_RETRIES):
            req = urllib.request.Request(url, data=body, headers=headers)
            try:
                with urllib.request.urlopen(req) as resp:
                    return json.loads(resp.read().decode("utf-8"))
            except urllib.error.HTTPError as e:
                if e.code == 429:
                    # Rate limited -- exponential backoff
                    wait = BACKOFF_BASE ** (attempt + 1)
                    print(f"    Rate limited, waiting {wait}s...")
                    time.sleep(wait)
                    continue
                elif e.code == 401:
                    # Token expired -- refresh and retry
                    self.token_mgr.access_token = ""
                    continue
                else:
                    error_body = e.read().decode("utf-8") if e.fp else ""
                    return {"code": e.code, "error": error_body}
            except urllib.error.URLError as e:
                if attempt < MAX_RETRIES - 1:
                    wait = BACKOFF_BASE ** (attempt + 1)
                    print(f"    Network error, retrying in {wait}s: {e}")
                    time.sleep(wait)
                else:
                    return {"code": 0, "error": str(e)}

        return {"code": 0, "error": "Max retries exceeded"}


# ============================================================
# Data Loading
# ============================================================

def load_csv_records(filepath: str) -> list[dict[str, str]]:
    """Load records from a CSV file, excluding auto-generated fields."""
    records: list[dict[str, str]] = []
    with open(filepath, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            record = {}
            for key, value in row.items():
                if key in EXCLUDE_FIELDS:
                    continue
                if value:  # Skip empty values
                    record[key] = value
            if record:
                records.append(record)
    return records


def load_json_records(filepath: str) -> list[dict]:
    """Load records from a JSON seed data file."""
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, list):
        return data
    return [data]


# ============================================================
# Main
# ============================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Upload data to Zoho Creator via REST API v2.1",
    )
    parser.add_argument(
        "--config", required=True,
        help="Path to zoho-api.yaml config file",
    )
    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument(
        "--csv-dir",
        help="Directory containing CSV files to upload",
    )
    source_group.add_argument(
        "--json-dir",
        help="Directory containing JSON seed data files",
    )
    parser.add_argument(
        "--live", action="store_true",
        help="Actually push records to Zoho (default: mock mode)",
    )
    parser.add_argument(
        "--batch-size", type=int, default=MAX_BATCH_SIZE,
        help=f"Records per API request (max {MAX_BATCH_SIZE})",
    )
    args = parser.parse_args()

    # Load config
    if not os.path.exists(args.config):
        print(f"Error: Config not found: {args.config}", file=sys.stderr)
        sys.exit(1)

    config = parse_yaml(args.config)

    # Validate config
    token_mgr = TokenManager(config)
    if args.live:
        errors = token_mgr.validate()
        if errors:
            for e in errors:
                print(f"Config error: {e}", file=sys.stderr)
            sys.exit(1)

    api = CreatorAPI(config, token_mgr, live=args.live)
    batch_size = min(args.batch_size, MAX_BATCH_SIZE)

    mode = "LIVE" if args.live else "MOCK"
    print(f"Mode: {mode}")
    print(f"App: {config.get('owner', '?')}/{config.get('app', '?')}")
    print(f"Batch size: {batch_size}")
    print()

    # Process tables in dependency order
    total_records = 0
    total_batches = 0

    for access_table, zoho_form in UPLOAD_ORDER:
        # Find data file
        records: list[dict] = []
        source_file = ""

        if args.csv_dir:
            csv_path = os.path.join(args.csv_dir, f"{access_table}.csv")
            if os.path.exists(csv_path):
                records = load_csv_records(csv_path)
                source_file = csv_path
        elif args.json_dir:
            json_path = os.path.join(args.json_dir, f"{access_table.lower()}.json")
            if os.path.exists(json_path):
                records = load_json_records(json_path)
                source_file = json_path

        if not records:
            print(f"  SKIP: {access_table} (no data file found)")
            continue

        print(f"  {access_table} -> {zoho_form}: {len(records)} records")

        # Upload in batches
        for i in range(0, len(records), batch_size):
            batch = records[i:i + batch_size]
            batch_num = (i // batch_size) + 1
            total_batches_for_table = (len(records) + batch_size - 1) // batch_size

            result = api.add_records(zoho_form, batch)
            code = result.get("code", 0)

            if result.get("mock"):
                print(f"    [MOCK] Batch {batch_num}/{total_batches_for_table}: "
                      f"{len(batch)} records -> {result['url']}")
            elif code == 3000:
                print(f"    Batch {batch_num}/{total_batches_for_table}: "
                      f"{len(batch)} records uploaded successfully")
            else:
                error = result.get("error", "Unknown error")
                print(f"    ERROR: Batch {batch_num}/{total_batches_for_table}: "
                      f"code={code}, error={error}")

            total_batches += 1

        total_records += len(records)

    print(f"\n{'='*50}")
    print(f"Total: {total_records} records in {total_batches} batches ({mode} mode)")
    if not args.live:
        print("To actually upload, re-run with --live flag")


if __name__ == "__main__":
    main()
